#!/bin/bash

echo "⚠️  WARNING: This will rewrite git history to remove .env file"
echo "⚠️  This is necessary because sensitive credentials were exposed"
echo ""
echo "Steps to remove .env from history:"
echo ""
echo "1. First, ensure you have a backup of your repository"
echo "2. Install BFG Repo-Cleaner:"
echo "   brew install bfg"
echo ""
echo "3. Run BFG to remove .env file from history:"
echo "   bfg --delete-files .env"
echo ""
echo "4. Clean up the repository:"
echo "   git reflog expire --expire=now --all && git gc --prune=now --aggressive"
echo ""
echo "5. Force push to all branches:"
echo "   git push --force --all"
echo "   git push --force --tags"
echo ""
echo "Alternative using git-filter-repo (if you prefer):"
echo "   pip install git-filter-repo"
echo "   git filter-repo --path .env --invert-paths"
echo ""
echo "⚠️  IMPORTANT: After removing from history, you MUST:"
echo "1. Rotate all exposed credentials immediately"
echo "2. Update your local .env file with new credentials"
echo "3. Notify any team members to re-clone the repository"