name = "ag-grid-react-components-demo"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist-demo"

# Routes for demo.rozich.net/ag-grid-react-components
[[routes]]
pattern = "demo.rozich.net/ag-grid-react-components/*"
zone_name = "rozich.net"