name: Cleanup PR Preview on Merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  cleanup-preview:
    name: Cleanup PR Preview Deployment
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Destroy Preview Deployment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Cleaning up preview deployment for PR #${PR_NUMBER}"

          # Install wrangler
          npm install -g wrangler

          # Delete the preview from KV metadata
          wrangler kv key delete "ag-grid-react-components-pr-${PR_NUMBER}" \
            --namespace-id="$CLOUDFLARE_KV_NAMESPACE_ID" \
            --remote || true

          # Delete the API worker
          npx wrangler delete "ag-grid-demo-api-pr-${PR_NUMBER}" || true

          echo "✅ Preview deployment cleaned up"

      - name: Add cleanup comment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const comment = `🧹 **Preview Deployment Cleaned Up**

            The preview deployment for this PR has been removed.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
