name: Deploy Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Demo to Cloudflare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build demo
        run: npm run build:demo
        env:
          VITE_BASE_PATH: /ag-grid-react-components/

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare R2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Upload demo assets to R2
          # First, clean up the existing files
          echo "Removing old files from R2..."
          wrangler r2 object delete rozich-demos/ag-grid-react-components/ --remote --recursive || true

          # Upload all files from dist-demo
          echo "Uploading new files to R2..."
          cd dist-demo
          find . -type f | while read -r file; do
            # Remove leading ./ from the file path
            file_path="${file#./}"
            echo "Uploading: $file_path"
            wrangler r2 object put "rozich-demos/ag-grid-react-components/$file_path" --file="$file" --remote
          done

      - name: Update demo metadata
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
        run: |
          # Skip KV update for now - wrangler syntax has changed
          echo "Skipping KV metadata update - needs syntax update"

      - name: Purge Cloudflare cache
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          # Purge cache for the demo path
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"files":["https://demo.rozich.net/ag-grid-react-components/*"]}'
