name: Deploy Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Demo to Cloudflare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install API dependencies
        run: cd api && npm install

      - name: Build demo
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          DEPLOY_PATH: ag-grid-react-components
          VITE_BASE_PATH: /ag-grid-react-components/
        run: |
          # Generate version info
          node scripts/generate-version-info.js

          # Build demo
          npm run build:demo

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare R2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Determine deploy path
          DEPLOY_PATH="ag-grid-react-components"
          echo "Deploying to path: $DEPLOY_PATH"

          # Upload demo assets to R2
          # First, clean up the existing files
          echo "Removing old files from R2..."
          wrangler r2 object delete "rozich-demos/$DEPLOY_PATH/" --remote --recursive || true

          # Upload all files from dist-demo
          echo "Uploading new files to R2..."
          cd dist-demo
          find . -type f | while read -r file; do
            # Remove leading ./ from the file path
            file_path="${file#./}"
            echo "Uploading: $file_path"
            wrangler r2 object put "rozich-demos/$DEPLOY_PATH/$file_path" --file="$file" --remote
          done

      - name: Update demo metadata
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
        run: |
          # Update KV metadata to register demo with router
          DEPLOY_PATH="ag-grid-react-components"

          wrangler kv key put "$DEPLOY_PATH" \
            '{"name": "AG Grid React Components", "description": "Tree-shakeable React filter components for AG Grid", "updated": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' \
            --namespace-id="$CLOUDFLARE_KV_NAMESPACE_ID" \
            --remote

      - name: Deploy API Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd api
          npx wrangler deploy --env production

      - name: Purge Cloudflare cache
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          # Purge cache for the demo path
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"files":["https://demo.rozich.net/ag-grid-react-components/*"]}'
